spring:
  jmx:
    enabled: false
  cloud:
    gateway:
      routes:
      # ======================================
      - id: after_route
        uri: http://example.org
        predicates:
        - After=2022-01-20T17:42:47.789-07:00[America/Denver]
        - Path=/**

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

management.endpoints.web.exposure.include: '*'
